### ISSUE TITLE
Use logo in page header

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo-doc#7]
The current page header "Nemo Rule Engine" should start with the "circled N" logo, followed by Nemo in Comfortaa bold, followed by "Graph Rule Engine" in Comfortaa normal, possibly a bit smaller (check what looks good). Comfortaa should be available as a Web font from Google.

**Comment by mmarx** [comment]
It's probably easiest to just prepare a horizontal variant of the logo, since starlight doesn't allow styling the `siteTitle` attribute, but can replace the whole title with the logo (different logos can be used for the dark and light themes). Alternatively, this would require overriding starlight's `SiteTitle` component to integrate the styling.
